### ISSUE TITLE
Feature: User can type HTML, CSS, and JavaScript into separate editors and run it. 

### ISSUE THREAD

**Issue by jsygo** [jsygo/webbin#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can type HTML, CSS, and JavaScript into separate editors and run it. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can type HTML into a code editor. User can add styling by typing CSS into a different editor. User can add interactivity by typing JavaScript into a different editor. There will be tabs in the navbar to switch between the different code editors. When the user clicks the "run" button, the output of the HTML will be displayed. On mobile, running the code will view swap to the output and the "run" button changes to "code" which brings you back to the editor. On desktop, the editor and output are side by side.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-02 at 12 44 40 PM](https://user-images.githubusercontent.com/87832078/139941820-30bdf66e-f3fa-4047-9349-ec340ff095c7.png)
![Screen Shot 2021-11-02 at 12 45 02 PM](https://user-images.githubusercontent.com/87832078/139941823-1c092f78-c2c1-430f-9985-0faa579c0f43.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component for the HTML editor
- [x] Create a component for the CSS editor
- [x] Create a component for the JavaScript editor
- [x] Style editors and output
- [x] Create a component for the iframe output
- [x] Create a component for tab nav bars
- [x] Create a page for the editors and output
- [x] Parse through the HTML, CSS, and JavaScript inputs and concatenate them together into one HTML document string
- [x] Update iframe output component to display the HTML document
- [x] Create a page for My Projects
- [x] Create a modal component
- [x] View swap between code and output on mobile, but not on desktop

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
