### ISSUE TITLE
Feature: User can sign up

### ISSUE THREAD

**Issue by jsygo** [jsygo/webbin#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can sign up for an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will land on the sign in page. If they don't have an account yet, they can switch to the sign up page. The user inputs a username and password. If the username is already taken, the user must choose a different username. Once the user creates an account, they will be taken to the sign-in page.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to receive a request at a sign-up route.
- [ ] hash the password and insert the username and hashed password into the 'users' table.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Add sign-up and sign-in actions to the auth form.
- [ ] Depending on the action, direct the user to the correct page.
- [ ] Add a click target to switch between sign-up and sign-in.
- [ ] When the user submits username and password, send a fetch to the server.
- [ ] If the server responds that the username is taken, notify the user to choose a different username.
- [ ] If the account is successfully registered, redirect to the sign-in page.

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
