### ISSUE TITLE
Feature: User can save a project.

### ISSUE THREAD

**Issue by jsygo** [jsygo/webbin#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a project.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Pressing the "save" button will make a modal pop up confirming the project was saved.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-02 at 1 11 31 PM](https://user-images.githubusercontent.com/87832078/139945102-41cb4ecf-60fe-45d9-a50e-2d1833dbaf9b.png)
![Screen Shot 2021-11-02 at 1 11 58 PM](https://user-images.githubusercontent.com/87832078/139945106-4cbcdfd9-682a-4b37-821b-9270401d7e81.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create the "users" "projects" "projectPermissions" tables
- [x] Update `data.sql` to insert a default user for testing

### ☁️ Server

- [x] Update `server/index.js` to receive a post to insert a new project int the "project" and "projectPermissions" tables
- [x] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] When user clicks save button, use fetch to send a post to save a project to the server
- [ ] Show modal confirming project was saved
### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
