### ISSUE TITLE
Feature: User can view and edit saved project.

### ISSUE THREAD

**Issue by jsygo** [jsygo/webbin#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view and edit saved project.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking the "projects" button will take the user to a page allowing them to select their own projects, or to explore other projects. Selecting their own projects will take the user to a list of all their saved projects. Clicking one will take them to the output on mobile, and to the output and editor on desktop. User can edit the code of the project.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-02 at 2 46 52 PM](https://user-images.githubusercontent.com/87832078/139956432-ba8ba822-4050-441d-8cd2-d79fac3f3967.png)
![Screen Shot 2021-11-02 at 2 47 06 PM](https://user-images.githubusercontent.com/87832078/139956434-7e7af83a-faf1-4d9d-925a-14f4f033f31f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to receive a get request and get all project names for the current user.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] when my projects list mounts, fetch users projects from database
- [x] render a list of user projects
- [x] when user clicks on project, that project is displayed and can be edited
- [x] if a user saves a project that is already in the database, that project is updated

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by jsygo** [comment]
## Switch to Hash Routing

- [x] When user clicks the create button on the new project modal, save a new project in the database under that name
- [x] Once the new project is saved, switch pages to the editor and output, with the new projects projectId as the URLSearchParams
- [x] When the editor and output mount, make a fetch for the name and code content of the projectId in the url params
- [x] Set the label of the output to the name of the project, and pass the code content down to the editor container.
- [x] When the user saves a project, make a patch request to the current projectId in the url params
- [x] When the user views a project, switch pages to the editor and output, with that projects projectId in the url params
