### ISSUE TITLE
Feature: User can delete a saved project.

### ISSUE THREAD

**Issue by jsygo** [jsygo/webbin#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can delete a saved project.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the gear icon to open project options. When the user selects delete, a modal will pop up to confirm they want to delete the project.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-02 at 3 11 49 PM](https://user-images.githubusercontent.com/87832078/139958970-bf1427c7-e341-4cae-8c60-afc6a8067aa9.png)
![Screen Shot 2021-11-02 at 3 12 06 PM](https://user-images.githubusercontent.com/87832078/139958975-99429701-102b-4d1d-b146-f4391dfb1e41.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to receive a delete request with a projectId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add a gear icon to the output label
- [x] Create a options list that appears when the user clicks the gear
- [x] When the user clicks delete, make a modal appear that makes the user confirm they want to delete the project
- [x] When the user confirms, send a fetch to the server to delete the project

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
