### ISSUE TITLE
Feature: User can sign in to an account.

### ISSUE THREAD

**Issue by jsygo** [jsygo/webbin#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in to an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can input username and password on the sign in form. If the login info is valid, the user will be taken to their projects list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-02 at 3 26 42 PM](https://user-images.githubusercontent.com/87832078/139960424-43974941-7a8e-4609-9350-54eefe23a756.png)
![Screen Shot 2021-11-02 at 3 26 53 PM](https://user-images.githubusercontent.com/87832078/139960427-7b6031f3-fad1-48c6-b17a-694b9e3cb873.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to receive a post request for a sign in and verify the password
- [x] If the password is incorrect, throw an error
- [x] If the password is correct, create a payload with the userId and username
- [x] create a JSON web token with the payload
- [x] respond to the client with the token and the user
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for a sign in form
- [x] Create a page for sign in
- [x] if there is no user in state, redirect to sign in
- [x] when the user inputs a username and password on the auth form, send a fetch to the server's sign in route with the username and password
- [x] store the token from the server response in local storage
- [x] store the user from the server response in the state and context
- [x] redirect to home

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
