### ISSUE TITLE
Feature: User can allow other users to edit their projects.

### ISSUE THREAD

**Issue by jsygo** [jsygo/webbin#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can allow other users to edit their projects.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add collaborators from the project options. Users can search for other users by username. When they select another user, a modal will pop up confirming that the user will be added to the project. This will allow that user to edit the code of the original project without having to save it as their own.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-02 at 3 49 02 PM](https://user-images.githubusercontent.com/87832078/139962527-c4f07b2b-f1e9-4db2-ab31-bcd02e2e6410.png)
![Screen Shot 2021-11-02 at 3 50 20 PM](https://user-images.githubusercontent.com/87832078/139962529-d61553fb-df2f-49a0-8b13-1052bd401e80.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to receive a post request at a 'share-project' route
- [x] the server will insert the projectId and the userId of the project into the 'projectPermissions' table
- [x] Add a get route that will respond with a list of all users
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] When the my projects page is loaded, also fetch the projects that a user has permissions for
- [x] Use the creatorId of each project to display the username of who made the project
- [x] Add a share option to the project options
- [x] when the user chooses share, make a fetch to get a list of all users
- [x] display a modal that allows the user to search through the list of users
- [x] when the user selects another user, display a modal confirming that they want to share
- [x] if the user confirms, send a fetch to the server to add that user to the 'projectPermissions'
- [x] add media queries to fix width of project list on mobile

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
